### ISSUE TITLE
Error block not being called

### ISSUE THREAD

**Issue by pspeter3** [pirj/padrino-cancan#1]
I put the following code in my app.rb but the error block is not being used.

``` ruby
error CanCan::AccessDenied do
  403
end
```

**Comment by pirj** [comment]
Seems that error block is not called because of issue #2

**Comment by pspeter3** [comment]
I'm still having the error block ignored even with issue #2 resolved

**Comment by pirj** [comment]
What happens if unauthorized user hits secured route? CanCan::AccessDenied should be fired.
Can you please attach your Gemfile, backtrace and controller code?

**Comment by pirj** [comment]
Cannot reproduce
