### ISSUE TITLE
Abilities not loaded

### ISSUE THREAD

**Issue by ngelx** [pirj/padrino-cancan#3]
Hi, thanks for this gem!

I'm having some troubles in geting padrino-cancan work. 

I have something like this in model/ability.rm

```
class Ability
include CanCan::Ability

def initialize(user)
  @user = user || User.new # for guest
  @user.roles.each { |role| send(role) }

  if @user.roles.size == 0
    can :create, :session #for guest without roles, only can login
  end
end
.....
 # Admin abilities
 def admin
   supervisor
   can :manage, User
 end

end
```

And in controller something like:

```
get :dump, :map => "/session/dump", :provides => [:json] do
  authorize! :view, User
  ....
end
```

But when I try that route with an admin user ... CanCan::AccesDenied is thrown.

CanCan seems to be working okay (user with id 3 is the same one that I used above)

```
padrino c

$> u = User.find(3)
$> u.is?("admin")
=> true 
$> a = Ability.new(u)
$> a.can?(:read,User)
 => true 
```

The problem seems to be in the [**current_ability**](https://github.com/pirj/padrino-cancan/blob/master/lib/padrino-cancan/helpers.rb#L4) method inside the gem helper 

```
def current_ability
   @ability ||= Ability.new(current_account, registered_abilities)
end
```

I overwrite this method with one in my own app helper and now seems to work as expected.

```
def current_ability
  @ability ||= Ability.new(current_account)
end
```

That makes me wonder what those registerd_abilities are for and if It is okay just to remove them?

Thanks

**Comment by pirj** [comment]
Hi,

You don't have to create a separate ability.rb file, just include the role definitions in your App file and add `register Padrino::CanCan`.
Please disregard the gist, it is outdated and has been created before the gem appeared.
You don't have to `@user.roles.each { |role| send(role) }`, this is done automatically for you.

Example:

```
class App < Padrino::Application
  register Padrino::CanCan

  error CanCan::AccessDenied do
    403
  end

  role [:manager, :reports, :admin] do
    can [:index, :view, :find, :search], Manufacturer
    can :index, [Manufacturer, Factory, Brand]
  end
end
```

that's it. If you want abilities to be a separate file, put them in a module and include to the App file.

If you don't like the DSL provided by this gem hold on for a week or so, i'm working on a different one, which is more model than controller security based (take a look for a rails/AR specific one at https://github.com/roundlake/heimdallr).
