### ISSUE TITLE
Because I'm super lazy and I'm sure others are too.

### ISSUE THREAD

**Issue by skull-squadron** [pirj/padrino-cancan#4]
`padrino-gen plugin cancan`

Haven't looked yet, but how hard can it be to get this working?

**Comment by skull-squadron** [comment]
https://github.com/padrino/padrino-framework/tree/master/padrino-gen/lib/padrino-gen/generators

**Comment by pirj** [comment]
Unless you are turbo lazy, please describe what you expect it to do. Preferrably send a pull request adding amfailing spec.
