### ISSUE TITLE
Access to account instance not avaliable

### ISSUE THREAD

**Issue by sliaquat** [pirj/padrino-cancan#5]
Say if I want to make sure that a user can only edit his own information, based on the info at https://github.com/pirj/padrino-cancan, the following should have been possible:

```
role [:restaurant_owner] do
  can :edit, Restaurant, :account => account
end
```

but I get:

undefined local variable or method `account' for #Padrino::CanCan::Ability:0x007f80f3b28600

if I am doing it wrong, please let me know how can I restrict access based on account particulars?

**Comment by pirj** [comment]
Please follow [this example app](https://gist.github.com/pirj/6e7afad5bbcf354f3e5b):

``` ruby
class Ability
  include CanCan::Ability

  def initialize account
...    
    allow [:external, :manager, :manufacturer, :admin] do
      can [:edit, :update], :account => account
    end
...
```

This should give you an idea what to do.

**Comment by pirj** [comment]
Basically you should replace `account` with `current_user` or what you initialize your Ability with.
